### ISSUE TITLE
problems with Circular tab

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/DiffusionDemo#1]
1. When the demo loads, the Circular tab defaults to 5 steps around the circle, but the Step Size shows 45, which is incorrect.
2. I think it's computing step size incorrectly. If we're doing a full circle (0 to 360) and we ask for 10 steps, then the step size should be 36 degrees, but the computed step size is 40 degrees. We're calculating 360/(N-1) instead of 360/N. In other words, we're failing to count the initial angle as a step. This is unintuitive.
3. If I click and drag to select the contents of the Number of Steps window and type "16", then the Step Size window shows Error. I don't know why.
4. The step size window looks just like the other windows, but it's display-only; it's not editable. Can we change the appearance of the window to distinguish it from the editable ones? Maybe give it a gray background.

**Comment by akameswa** [comment]
[Addressing 2]
- There are two possible interpretations:
    -  If we want the steps to be 10 including the initial angle as a step, then the step size would be 40 degrees.
        - [0, 40, 80, 120, 160, 200, 240, 280, 320, 360]. 
    - If we use the step size as 36 degrees including the initial angle as a step, then there would be 11 steps and not 10.
        -  [0, 36, 72, 108, 144, 180, 216, 252, 288, 324, 360]. 
 
     Both the interpretations has step size calculation as 360/(N-1). This is what the code is based on. 
I believe it would be easier if we exclude the initial angle in calculation. 
- For example, if we use 10 steps not including the initial angle as a step, the step size would be 36 degrees (360/N). And the angles would be [36, 72, 108, 144, 180, 216, 252, 288, 324, 360]

Please let me know if you would like to keep the old calculation or incorporate the new one. I shall make the changes accordingly.

**Comment by akameswa** [comment]
[Addressing 1 and 4] 
Updated in dev branch. Will merge into main after resolving 2.

**Comment by akameswa** [comment]
[Addressing 3]
This could be occurring because of how the current step size calculation is done (360/(N-1). The step size field constantly watches the changes done to steps and angles, updating its value. 

Gradio could be registering 1 instead of 16. This makes the step size calculation to be divided by 0, thus causing the error. I did place restrictions for the slider but it may not have been enforced when typing in the field. The error may go away if we incorporate the new step size calculation.

**Comment by touretzkyds** [comment]
I guess it comes down to whether you think of "steps" as changes or as positions. I tend to think of them as changes and so I do not count the initial position. So if I ask for two steps around the circle then I would expect them to be  at 180 degrees and 360 degrees, and would not count the initial 0 degrees as a step. We'd have three images but they were reached in two steps (0 to 180 and 180 to 360).

**Comment by akameswa** [comment]
> I guess it comes down to whether you think of "steps" as changes or as positions. I tend to think of them as changes and so I do not count the initial position. So if I ask for two steps around the circle then I would expect them to be at 180 degrees and 360 degrees, and would not count the initial 0 degrees as a step. We'd have three images but they were reached in two steps (0 to 180 and 180 to 360).

Understood. I will make the necessary changes that calculates the step size as 360/N without including the initial angle.
